. "$LIB_DIR/colors.sh"

printHelp() {
    echo "Usage: hlrunner <command> [arguments]"
    echo ""
    echo "${txtBold}> ${txtGreen}Available Commands${colorReset}:"
    echo "    hlrunner init <name>     - Create a new stack from template"
    echo "    hlrunner up <stack>      - Start a stack"
    echo "    hlrunner down <stack>    - Stop a stack"
    echo "    hlrunner build <stack>   - Build stack images"
    echo "    hlrunner logs <stack>    - View logs for a stack"
    echo "    hlrunner pull <stack>    - Pull latest images"
    echo "    hlrunner upgrade <stack> - Pull, down, up"
    echo "    hlrunner list            - List all stacks"
    echo "    hlrunner ps              - Show running containers"
    echo "    hlrunner psp             - Show running containers, with Ports"
    echo "    hlrunner upall           - Start all stacks"
    echo "    hlrunner downall         - Stop all stacks"
    echo "    hlrunner pullall         - Pull all stacks"
    echo "    hlrunner upgradeall      - Upgrade all stacks"
    echo ""
    echo "${txtBold}> ${txtYellow}Environment${colorReset}:"
    echo "    HLR_STACKS_PATH - Path to stacks (default: current directory)"
    echo "    HLR_DATA_DIR    - Path to lib/templates (default: script-relative)"
    echo ""
    echo "${txtBold}> Examples:${colorReset}"
    echo "    hlrunner init mystack"
    echo "    hlrunner up nginx"
    echo "    hlrunner upgrade homepage"
    echo "    hlrunner upgradeall"
    echo "    HLR_STACKS_PATH=~/mystacks hlrunner list"
}
